package util

import (
	"bytes"
	"go/format"
	"html/template"
	"io/ioutil"
	"os"
	"strings"
)

const (
	DefaultStructSpacing = 15
)

type astDefElement struct {
	Name  string
	TType string
}

type astDef struct {
	Name           string
	PackageName    string
	ImportRequired bool
	Elements       []astDefElement
}

var astDefinition = []astDef{
	{"Binary", "expression", true, []astDefElement{{"Left", "Expression"}, {"Operator", "scanner.Token"}, {"Right", "Expression"}}},
	{"Grouping", "expression", false, []astDefElement{{"Expr", "Expression"}}},
	{"Literal", "expression", false, []astDefElement{{"Value", "interface{}"}}},
	{"Unary", "expression", true, []astDefElement{{"Operator", "scanner.Token"}, {"Right", "Expression"}}},
}

func GenerateAst(homeDir, packageName string) {

	basePath := homeDir + string(os.PathSeparator) + packageName
	if _, err := os.Stat(basePath); os.IsNotExist(err) {
		err := os.Mkdir(basePath, os.ModePerm)
		checkErr(err, "Could not create path: "+basePath+"!\nError:"+err.Error())
	}
	writeToFile(basePath+string(os.PathSeparator)+"Warning.md", generateWarining())

	t, err := template.ParseFiles(homeDir + string(os.PathSeparator) + "util" + string(os.PathSeparator) + "astElementTemplate.tmpl")
	checkErr(err, "Could not parse template!")
	for _, element := range astDefinition {
		var codeBuffer bytes.Buffer
		element.PackageName = packageName
		err = t.Execute(&codeBuffer, element)
		checkErr(err, "Could not generate template!")

		formatedCode, err := format.Source(codeBuffer.Bytes())
		checkErr(err, "Could not format source code!")
		filePointer, err := os.Create(basePath + string(os.PathSeparator) + strings.ToLower(element.Name) + ".go")
		checkErr(err, "Could not open file pointer!")
		_, err = filePointer.Write(formatedCode)
		checkErr(err, "Could not write to file pointer!")
	}

}

func writeToFile(file string, content string) {
	println(file)
	err := ioutil.WriteFile(file, []byte(content), 0644)
	checkErr(err, "Could not write file: "+file+"!\nWith content: \n"+content+"\nCowardly refusing to carry on! Exiting!")
}

func checkErr(err error, msg string) {
	if err != nil {
		panic(msg + "\nError:" + err.Error())
	}
}

func generateWarining() string {
	return `# Warning

This folder is autogenerated.
Do not modify it's content! It might be overwritten!'

## These files get overwritten:
- expression/binary.go
- expression/expression.go
- expression/grouping.go
- expression/literal.go
- expression/unary.go
- expression/Warning.md

`
}
